server:
  # 配置端口
  port: 8080
  # 配置context-path访问根路径
  #servlet:
  #  context-path: /api


# 外部配置
book.name: 世界五百强
book.author: Jack


# Log
logging:
  level:
    root: info
  #日志文件
  # file: /home/baiyu/Desktop/log.log

# Spring基本配置
spring:
  # 配置Profile不同环境使用不同配置信息
  profiles:
    active: dev
  # 网络配置类似web.xml中的CharacterEncodingFilter
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # 配置国际化 可以包括多个，以逗号分隔。每一个ResourceBundle
  messages:
    basename: i18n/messages

# Spring自动配置原理展示
hello:
  content: Custom AutoConfiguration

# 输出日志，打印自动配置信息
debug: true


